========TASK 3========
Task 3.1: NumPy Basics

1.	Create a 1D NumPy array of 10 random integers between 1 and 100.


In [56]:
import numpy as np
arr1=np.random.randint(1,101,size=10)
arr1

array([27, 13,  7, 27, 38, 10,  1, 28, 83, 96], dtype=int32)

⦁	Print the maximum element of the array

In [57]:
print(np.max(arr1))

96


⦁	Print the minimum element of the array.

In [58]:
print(np.min(arr1))

1


⦁	Print the mean of the array.

In [59]:
print(np.mean(arr1))

33.0


⦁	Print the sum of all elements.


In [60]:
print(np.sum(arr1))

330


⦁	Find and print the index of the maximum element.

In [61]:
print(np.argmax(arr1))

9


⦁	Find and print the index of the minimum element.


In [62]:
print(np.argmin(arr1))

6


⦁	Sort the array in ascending order and print it.

In [63]:
print(np.sort(arr1))

[ 1  7 10 13 27 27 28 38 83 96]


Task 3.2: NumPy Indexing and Slicing
1.	Create a 3×3 NumPy array with random integers between 1 and 20.

In [64]:
arr2=np.random.randint(1,21,size=(3,3))
arr2

array([[17, 14, 13],
       [ 5, 14, 13],
       [13, 16,  4]], dtype=int32)

⦁	Print the entire array.

In [65]:
print(arr2)

[[17 14 13]
 [ 5 14 13]
 [13 16  4]]


⦁	Print the first row of the array.

In [66]:
arr2[0]

array([17, 14, 13], dtype=int32)

⦁	Print the second column of the array.

In [67]:
arr2[:,1]

array([14, 14, 16], dtype=int32)

⦁	Print the element at position (2,2).

In [68]:
arr2[2,2]

np.int32(4)

⦁	Print the sub-array containing the first two rows and first two columns.

In [69]:
arr2[:2,:2]

array([[17, 14],
       [ 5, 14]], dtype=int32)

⦁	Replace the middle element of the matrix with 99 and print the modified array.

In [70]:
arr2[1,1]=45
arr2

array([[17, 14, 13],
       [ 5, 45, 13],
       [13, 16,  4]], dtype=int32)

Task 3.3: NumPy Vectorized Operations
1.	Generate two random integer arrays of size 10 with values between 1 and 20

In [71]:
crr=np.random.randint(1,21,size=10)
print("array crr=",crr)
drr=np.random.randint(1,21,size=10)
print("array drr=",drr)

array crr= [13  4 15 17  1  7 18  2  3 14]
array drr= [ 3 15  3 18  7  7  8  1  7 12]


⦁	Perform element-wise addition, subtraction, multiplication, and division between the arrays.

In [72]:
#addition
crr+drr


array([16, 19, 18, 35,  8, 14, 26,  3, 10, 26], dtype=int32)

In [73]:
#subtraction
crr-drr

array([ 10, -11,  12,  -1,  -6,   0,  10,   1,  -4,   2], dtype=int32)

In [74]:
# multiplication
crr*drr

array([ 39,  60,  45, 306,   7,  49, 144,   2,  21, 168], dtype=int32)

In [75]:
#division
drr/crr


array([0.23076923, 3.75      , 0.2       , 1.05882353, 7.        ,
       1.        , 0.44444444, 0.5       , 2.33333333, 0.85714286])

⦁	Square every element in the first array.

In [76]:
crr**2

array([169,  16, 225, 289,   1,  49, 324,   4,   9, 196], dtype=int32)

⦁	Find the dot product of the two arrays.

In [77]:
np.dot(crr,drr)

np.int32(841)

⦁	Sort the second array in ascending order and print it.

In [78]:
np.sort(drr)
#for descending order
#np.sort(drr)[::-1]


array([ 1,  3,  3,  7,  7,  7,  8, 12, 15, 18], dtype=int32)