========TASK 3========
Task 3.1: NumPy Basics

1.	Create a 1D NumPy array of 10 random integers between 1 and 100.


In [2]:
import numpy as np
arr1=np.random.randint(1,101,size=10)
arr1

array([ 2,  7, 67, 34, 90, 63, 64, 78,  8, 98], dtype=int32)

⦁	Print the maximum element of the array

In [3]:
print(np.max(arr1))

98


⦁	Print the minimum element of the array.

In [4]:
print(np.min(arr1))

2


⦁	Print the mean of the array.

In [5]:
print(np.mean(arr1))

51.1


⦁	Print the sum of all elements.


In [6]:
print(np.sum(arr1))

511


⦁	Find and print the index of the maximum element.

In [7]:
print(np.argmax(arr1))

9


⦁	Find and print the index of the minimum element.


In [8]:
print(np.argmin(arr1))

0


⦁	Sort the array in ascending order and print it.

In [9]:
print(np.sort(arr1))

[ 2  7  8 34 63 64 67 78 90 98]


Task 3.2: NumPy Indexing and Slicing
1.	Create a 3×3 NumPy array with random integers between 1 and 20.

In [10]:
arr2=np.random.randint(1,21,size=(3,3))
arr2

array([[ 1,  8,  9],
       [12, 20, 10],
       [ 8, 20, 18]], dtype=int32)

⦁	Print the entire array.

In [11]:
print(arr2)

[[ 1  8  9]
 [12 20 10]
 [ 8 20 18]]


⦁	Print the first row of the array.

In [12]:
arr2[0]

array([1, 8, 9], dtype=int32)

⦁	Print the second column of the array.

In [13]:
arr2[:,1]

array([ 8, 20, 20], dtype=int32)

⦁	Print the element at position (2,2).

In [14]:
arr2[2,2]

np.int32(18)

⦁	Print the sub-array containing the first two rows and first two columns.

In [15]:
arr2[:2,:2]

array([[ 1,  8],
       [12, 20]], dtype=int32)

⦁	Replace the middle element of the matrix with 99 and print the modified array.

In [16]:
arr2[1,1]=45
arr2

array([[ 1,  8,  9],
       [12, 45, 10],
       [ 8, 20, 18]], dtype=int32)

Task 3.3: NumPy Vectorized Operations
1.	Generate two random integer arrays of size 10 with values between 1 and 20

In [17]:
crr=np.random.randint(1,21,size=10)
print("array crr=",crr)
drr=np.random.randint(1,21,size=10)
print("array drr=",drr)

array crr= [ 1 14  6  7 10  1 18  1  2  3]
array drr= [10 10 11  4  9 16  1  5 13  5]


⦁	Perform element-wise addition, subtraction, multiplication, and division between the arrays.

In [18]:
#addition
crr+drr


array([11, 24, 17, 11, 19, 17, 19,  6, 15,  8], dtype=int32)

In [19]:
#subtraction
crr-drr

array([ -9,   4,  -5,   3,   1, -15,  17,  -4, -11,  -2], dtype=int32)

In [20]:
# multiplication
crr*drr

array([ 10, 140,  66,  28,  90,  16,  18,   5,  26,  15], dtype=int32)

In [21]:
#division
drr/crr


array([10.        ,  0.71428571,  1.83333333,  0.57142857,  0.9       ,
       16.        ,  0.05555556,  5.        ,  6.5       ,  1.66666667])

⦁	Square every element in the first array.

In [22]:
crr**2

array([  1, 196,  36,  49, 100,   1, 324,   1,   4,   9], dtype=int32)

⦁	Find the dot product of the two arrays.

In [23]:
np.dot(crr,drr)

np.int32(414)

⦁	Sort the second array in ascending order and print it.

In [24]:
np.sort(drr)
#for descending order
#np.sort(drr)[::-1]


array([ 1,  4,  5,  5,  9, 10, 10, 11, 13, 16], dtype=int32)